stages:
  - build
  - test
  - deploy
  - check

build:
  stage: build
  script:
    - make tarball

test:
  stage: test
  script: 
    - make test

check:
  stage: check
  script:
    - make check || (cat rcf.Rcheck/tests/testthat.Rout.fail && exit 1)
  allow_failure: true

deploy:
  stage: deploy
  script:
    - make install
  allow_failure: false
    
#deploy_collaudo:
#  stage: deploy
#  tags:
#    - collaudo
#  script:
#    - make install
#  allow_failure: true


coverage:
  stage: test
  script:
    - make coverage
    - Rscript -e 'covr::codecov()'
  allow_failure: true

