# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

repos:
  CRAN: https://cran.rstudio.com

r_packages:
  - covr
  - hash
  - doMC
  - xts
  - Rcpp
  - stringr
  - xlsx
  - tis
  
r_github_packages:
  - giupo/rprogressbar
  - giupo/rutils

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions=file.path("packrat", list.files(path="packrat", recursive=TRUE)))'