# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false
pandoc: false
latex: false

addons:
  apt:
    packages:
       - libxml2-dev
r:
  - release

warnings_are_errors: false

repos:
  CRAN: http://cran.rstudio.com

after_success:
  - make test
  - make codecov
 
  
