# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' tsWrite nativo
#'
#' Scrive una timeseries in formato CSV (legacy support)
#' @name tsWrite_nativo
#' @param series timeSeries
#' @param path percorso del file
#' @import Rcpp
#' @useDynLib rdataset
NULL

#' tsRead implementato nativamente.
#'
#' @name tsRead_nativo
#' @param path a path to the CSV file representing a timeseries
#' @return a `ts` object
#' @import Rcpp
#' @useDynLib rdataset
NULL

tsWrite_nativo <- function(series, path) {
    invisible(.Call('_rdataset_tsWrite_nativo', PACKAGE = 'rdataset', series, path))
}

tsRead_nativo <- function(path) {
    .Call('_rdataset_tsRead_nativo', PACKAGE = 'rdataset', path)
}

