# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' tsRead implementato nativamente.
#'
#' @name tsRead_nativo
#' @param path a path to the CSV file representing a timeseries
#' @return a `ts` object
#' @import Rcpp
#' @useDynLib rdataset
NULL

tsRead_nativo <- function(path) {
    .Call('rdataset_tsRead_nativo', PACKAGE = 'rdataset', path)
}

